<a href="https://colab.research.google.com/github/Girrajha/New-file-/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
Numerical python

# properties
1 it is  homogeneous (store in single )  datatypes
2 numpy is faseter that list

In [ ]:
# hoe to creat numpy


In [1]:
import numpy as np
# as - alosa use to create nickname

In [ ]:
# numpy function

1 np.array(list)
2

In [2]:
array = np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [3]:
arr2 = np.array(["python ",23.4,43])
arr2

array(['python ', '23.4', '43'], dtype='<U32')

In [4]:
arr3 = np.array([1,2,3,4,5,32.4])
arr3

array([ 1. ,  2. ,  3. ,  4. ,  5. , 32.4])

In [ ]:
# type casting

In [6]:
array1 = np.array([2,3,4,5,6,7.4],dtype = string )
array1

NameError: name 'string' is not defined

In [ ]:
# dimension in numpy array
1   0-D array

In [7]:
array0 = np.array(30)   # it is a one d arrray
array0.ndim

0

In [ ]:
2, one dimensionn array
it is a collection of multiple 0-d arrays
[23,232,43,454,3,64,65] it is a 1 d array

In [9]:
array1 = np.array([324,43,53,345,64],dtype=str)
print (array1,array.ndim)

['324' '43' '53' '345' '64'] 1


In [ ]:
3 two dimension array

[[1,2,3,4,55,6],[3,2,4,5,4,6,7]]
#collection on one d array it is known as 2 d arrray

In [10]:
array2 = np.array([[1,2,3,4,55,6],[3,2,4,5,4,6,7]])
print(array2,array2.ndim)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [11]:
# Ensure all inner lists have the same length
# Option 1: Make the first list the same length as the second
# array2 = np.array([[1,2,3,4,55,6, <add an element here>],[3,2,4,5,4,6,7]])

# Option 2: Make the second list the same length as the first
array2 = np.array([[1,2,3,4,55,6],[3,2,4,5,4,6]]) # Removed the last element '7'
print(array2,array2.ndim)

[[ 1  2  3  4 55  6]
 [ 3  2  4  5  4  6]] 2


In [ ]:
3, three dimension array

[[[1,2,3,4,55,6],[3,2,4,5,4,6,7]]]

In [13]:
array = np.array([[[1,2,3,4,55,6],[3,2,4,5,4,6]]])
print(array,array.ndim)

[[[ 1  2  3  4 55  6]
  [ 3  2  4  5  4  6]]] 3


In [ ]:
function of numpy

1. shape
# it is use to chk how many data in out code (raw,column)
2. reshape
# it is use to convert anrr into n d aarry
3. np.nditer
# it is use to itterate n d array
4. ndenumerate()
#return value as well as value
5 flatten and ravel
#both use to convert n d array to 1 d aaray
# flatten .. we can change in flatten array but original not change
6 tolist
# it is use to convert array  to list
7 np.zeros()
8 np.ones()





In [14]:
#shape
arr1 = np.array([2,3,4,5,6,7])
arr1.shape

(6,)

In [15]:
# reshape
#1d to 2d
#array1.reshape(row,column)
arr2 =  np.array([12,32,44,53,67,7,64,5635,35,546,75,453,])
new = reshape.arr2(2,6)

NameError: name 'reshape' is not defined

In [17]:
# reshape
#1d to 2d
#array1.reshape(row,column)
arr2 =  np.array([12,32,44,53,67,7,64,5635,35,546,75,453,])
# Correctly call the reshape method on the arr2 object
new = arr2.reshape(2,6)
new

array([[  12,   32,   44,   53,   67,    7],
       [  64, 5635,   35,  546,   75,  453]])

In [18]:
arr2 =  np.array([12,32,44,53,67,7,64,5635,35,546,75,453,])
for i in np.nditer(arr2):
  print(i)

12
32
44
53
67
7
64
5635
35
546
75
453


In [21]:
# prompt: 3 d array list

# Creating a 3D NumPy array
array3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i in nditer(array3):
  print(i)

NameError: name 'nditer' is not defined

In [23]:
# prompt: 3 d array list

# Creating a 3D NumPy array
array3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# Call nditer using the np prefix
for i in np.nditer(array3):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [25]:
# prompt: ndenumerate

# ndenumerate()
# return value as well as value

# Creating a 3D NumPy array
array3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i ,value in np.ndenumerate(array3):
  print(i,value)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


In [27]:
arr4 = np.array([[1,2,3,4],[2,3,4,5]])
new = arr4.flatten()
new[0]= 1000
print (new)

[1000    2    3    4    2    3    4    5]


In [28]:
arrr5 = np.array({1,2,3,4,5,6,7,7})
print(type(arrr5))
print(arrr5)

x = arrr5.tolsit()
print(x)

<class 'numpy.ndarray'>
{1, 2, 3, 4, 5, 6, 7}


AttributeError: 'numpy.ndarray' object has no attribute 'tolsit'

In [ ]:
arrr5 = np.array({1,2,3,4,5,6,7,7})
print(type(arrr5))
print(arrr5)

# Corrected the method name from tolsit() to tolist()
x = arrr5.tolist()
print(x)

In [29]:
# np.zeros()
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [30]:
#np.ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# np.full()
np.full(shape, value)

In [31]:
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [ ]:
# arrage()
np.arrange(start,endm,step)


In [ ]:
from typing import ValuesView
#linspace()
it return evenly space ValuesView



In [36]:
np.linspace(1,2,num=10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [ ]:
# identity()
it is use to create identity matrix

In [37]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#random
it is use to generate number

In [ ]:
random.randint(start,end.size(raw,col))

In [38]:
np.random.randint(1,100,(3,3))

array([[ 3, 20, 97],
       [ 6, 99,  8],
       [ 5, 53, 18]])

In [ ]:
#np.random.rand()
it return values 0 to 1
np.random.rand=(shape)

In [39]:
np.random.rand(8)

array([0.55219497, 0.54620305, 0.90841335, 0.14552051, 0.75358576,
       0.13715468, 0.83885282, 0.53692633])

In [ ]:
#random.randn
random.randn
it return sample from the normally distributed dataclass_transform
-3 to +3
infinite  ot infinite

In [40]:
np.random.randn(10)

array([ 0.07978805, -0.17344303, -0.78297818, -0.79497493,  0.51871255,
        0.74755163, -0.57029856,  1.14681542, -0.30126544, -1.16292156])

In [ ]:
#append()
it is use to add value in lat
np.append(array1,value , axis = none )
value >> nd array
axise-0 >> row
axos-1 >> coloumn


In [41]:
arr = np.random.randint(10,20,size=(2,3))
arr

array([[14, 15, 15],
       [16, 10, 18]])

In [42]:
np.append(arr,[[100,200,300]],axis=0)

array([[ 14,  15,  15],
       [ 16,  10,  18],
       [100, 200, 300]])

In [43]:
np.append(arr1 , arr2 , axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
# prompt: matrix opperation in numpy

# Matrix operations in numpy

# Matrix addition
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
sum_matrix = matrix1 + matrix2
print("Matrix Addition:")
print(sum_matrix)

# Matrix subtraction
diff_matrix = matrix1 - matrix2
print("\nMatrix Subtraction:")
print(diff_matrix)

# Matrix multiplication
product_matrix = np.dot(matrix1, matrix2)
print("\nMatrix Multiplication:")
print(product_matrix)

# Element-wise multiplication
element_wise_product = matrix1 * matrix2
print("\nElement-wise Multiplication:")
print(element_wise_product)

# Matrix transpose
transpose_matrix = matrix1.T
print("\nMatrix Transpose:")
print(transpose_matrix)

# Inverse of a matrix
# Need to import linear algebra module from numpy
from numpy.linalg import inv
try:
    inverse_matrix = inv(matrix1)
    print("\nInverse of Matrix 1:")
    print(inverse_matrix)
except np.linalg.LinAlgError:
    print("\nMatrix 1 is singular, cannot compute inverse.")

# Determinant of a matrix
from numpy.linalg import det
determinant_matrix1 = det(matrix1)
print("\nDeterminant of Matrix 1:")
determinant_matrix1

In [ ]:
np.floor()          # base
np.ceil()          #
np.around()


In [44]:
np.floor(4.5)

np.float64(4.0)